#include "cpp_generator.h"

#include <QDir>
#include <QSaveFile>
#include <QTextStream>
#include <QSet>

QString CppGenerator::sanitize(const QString& name)
{
    QString s = name;
    if (s.isEmpty()) s = "Unnamed";
    // simple sanitize: replace spaces and invalid chars with '_'
    for (int i = 0; i < s.size(); ++i) {
        const QChar c = s[i];
        if (!(c.isLetterOrNumber() || c == '_' )) s[i] = '_';
    }
    if (s[0].isDigit()) s.prepend('_');
    return s;
}

QString CppGenerator::cppTypeFor(ParamType t)
{
    switch (t) {
    case ParamType::UINT8: return "uint8_t";    case ParamType::UINT16: return "uint16_t";  case ParamType::UINT32: return "uint32_t";
    case ParamType::INT8:  return "int8_t";     case ParamType::INT16:  return "int16_t";   case ParamType::INT32:  return "int32_t";
    case ParamType::FLOAT: return "float";      case ParamType::DOUBLE: return "double";
    case ParamType::CHAR:  return "char";       case ParamType::CHAR_ARRAY: return "char"; // array handled separately
    default: return QString();
    }
}

QString CppGenerator::toLowerCamel(const QString& s)
{
    if (s.isEmpty()) return s;
    QString out = sanitize(s);
    out[0] = out[0].toLower();
    return out;
}

bool CppGenerator::generate(const ParamMetadata& root, const QString& outDir)
{
    QDir dir(outDir);
    if (!dir.exists()) {
        if (!dir.mkpath(".")) return false;
    }

    // traverse tree: generate for each struct node
    bool ok = true;
    QList<const ParamMetadata*> stack; stack.append(&root);
    while (!stack.isEmpty()) {
        const ParamMetadata* n = stack.takeLast();
        if (n->type == ParamType::STRUCT) {
            ok = generateStruct(*n, outDir) && ok;
        }
        for (const auto& c : n->children) stack.append(&c);
    }
    return ok;
}

bool CppGenerator::generateInstances(const ParamMetadata& root, const QVector<InstanceMetadata>& instances, const QString& outDir)
{
    return writeInstancesUnit(root, instances, outDir);
}

bool CppGenerator::generateInstancesJson(const ParamMetadata& root, const QVector<InstanceMetadata>& instances, const QString& outDir)
{
    return writeInstancesJsonUnit(root, instances, outDir);
}

static const ParamMetadata* findTypeNodeByPath(const ParamMetadata& root, const QString& path)
{
    // path like /Root/A/B
    QStringList parts = path.split('/', QString::SkipEmptyParts);
    if (parts.isEmpty()) return nullptr;
    if (parts.first() != root.name) return nullptr;
    const ParamMetadata* cur = &root;
    for (int i = 1; i < parts.size(); ++i) {
        bool ok=false;
        for (const auto& c : cur->children) { if (c.name == parts[i]) { cur = &c; ok=true; break; } }
        if (!ok) return nullptr;
    }
    return cur;
}

QString CppGenerator::renderAggregateInit(const ParamMetadata& typeNode, const InstanceMetadata& inst)
{
    QString s("{");
    bool first = true;
    for (const auto& field : typeNode.children) {
        if (!first) s += ", "; first = false;
        if (field.type == ParamType::STRUCT) {
            // find child instance matching this field
            const InstanceMetadata* childInst = nullptr;
            for (const auto& ci : inst.children) if (ci.name == field.name) { childInst = &ci; break; }
            if (childInst) {
                s += renderAggregateInit(field, *childInst);
            } else {
                s += renderAggregateInit(field, InstanceMetadata());
            }
        } else if (field.type == ParamType::CHAR_ARRAY && field.arraySize > 0) {
            const QString v = inst.values.value(field.name).toString();
            s += "\"" + v + "\"";
        } else if (field.type == ParamType::ENUM) {
            const QString v = inst.values.value(field.name).toString();
            s += v.isEmpty()? QString("0") : v; // 简化：需与枚举定义名一致
        } else if (field.type == ParamType::FLOAT || field.type == ParamType::DOUBLE) {
            const QString v = inst.values.value(field.name).toString();
            s += v.isEmpty()? QString("0.0f") : v;
        } else {
            const QString v = inst.values.value(field.name).toString();
            s += v.isEmpty()? QString("0") : v;
        }
    }
    s += "}";
    return s;
}

bool CppGenerator::writeInstancesUnit(const ParamMetadata& root, const QVector<InstanceMetadata>& instances, const QString& outDir)
{
    if (instances.isEmpty()) return true;
    QSaveFile hf(outDir + "/Instances.h");
    if (!hf.open(QIODevice::WriteOnly | QIODevice::Truncate)) return false;
    QTextStream hout(&hf); hout.setCodec("UTF-8");
    hout << "// Auto-generated by SimParamEditor\n#pragma once\n\n";
    // include：收集所有涉及到的 struct 以及其子 struct，确保复合结构的头文件全部包含
    QSet<QString> typeNames;
    struct Walker {
        static void collect(const ParamMetadata& t, QSet<QString>& names) {
            if (t.type != ParamType::STRUCT) return;
            names.insert(t.name);
            for (int i = 0; i < t.children.size(); ++i) {
                const ParamMetadata& c = t.children.at(i);
                if (c.type == ParamType::STRUCT) collect(c, names);
            }
        }
    };
    for (const auto& inst : instances) {
        const ParamMetadata* tn = findTypeNodeByPath(root, inst.typePath);
        if (tn) Walker::collect(*tn, typeNames);
    }
    for (const QString& n : typeNames) hout << "#include \"" << sanitize(n) << ".h\"\n";
    hout << "\n";
    if (!hf.commit()) return false;

    QSaveFile sf(outDir + "/Instances.cpp");
    if (!sf.open(QIODevice::WriteOnly | QIODevice::Truncate)) return false;
    QTextStream sout(&sf); sout.setCodec("UTF-8");
    sout << "// Auto-generated by SimParamEditor\n";
    sout << "#include \"Instances.h\"\n";
    sout << "#include <string>\n";
    // json head-only（用户将提供 third_party/json/json.hpp）
    sout << "#include \"json.hpp\"\n\n";
    sout << "using nlohmann::json;\n\n";
    for (const auto& inst : instances) {
        const ParamMetadata* tn = findTypeNodeByPath(root, inst.typePath);
        if (!tn) continue;
        const QString typeName = sanitize(tn->name);
        const QString instName = toLowerCamel(inst.name);
        sout << typeName << " " << instName << " = " << renderAggregateInit(*tn, inst) << ";\n";
    }

    // 预留：生成 to_json/from_json 的简化示例（仅聚合 -> json 原型）
    sout << "\n// TODO: generate per-type to_json/from_json if needed.\n";
    return sf.commit();
}

void CppGenerator::renderToJson(QTextStream& out, const ParamMetadata& typeNode, const QString& varName, const QString& jsonVar, int indent)
{
    const QString ind(indent, ' ');
    out << ind << jsonVar << " = json::object();\n";
    for (int i = 0; i < typeNode.children.size(); ++i) {
        const ParamMetadata& c = typeNode.children.at(i);
        if (c.type == ParamType::STRUCT) {
            out << ind << "{ json child;\n";
            renderToJson(out, c, varName + "." + sanitize(c.name), "child", indent + 2);
            out << ind << jsonVar << "[\"" << sanitize(c.name) << "\"] = child; }\n";
        } else {
            out << ind << jsonVar << "[\"" << sanitize(c.name) << "\"] = " << varName << "." << sanitize(c.name) << ";\n";
        }
    }
}

void CppGenerator::renderFromJson(QTextStream& out, const ParamMetadata& typeNode, const QString& varName, const QString& jsonVar, int indent)
{
    const QString ind(indent, ' ');
    for (int i = 0; i < typeNode.children.size(); ++i) {
        const ParamMetadata& c = typeNode.children.at(i);
        if (c.type == ParamType::STRUCT) {
            out << ind << "if(" << jsonVar << ".contains(\"" << sanitize(c.name) << "\")) {\n";
            out << ind << "  const json& child = " << jsonVar << "[\"" << sanitize(c.name) << "\"];\n";
            renderFromJson(out, c, varName + "." + sanitize(c.name), "child", indent + 2);
            out << ind << "}\n";
        } else {
            out << ind << "if(" << jsonVar << ".contains(\"" << sanitize(c.name) << "\")) " << varName << "." << sanitize(c.name) << " = " << jsonVar << "[\"" << sanitize(c.name) << "\"];\n";
        }
    }
}

bool CppGenerator::writeInstancesJsonUnit(const ParamMetadata& root, const QVector<InstanceMetadata>& instances, const QString& outDir)
{
    if (instances.isEmpty()) return true;
    QSaveFile sf(outDir + "/InstancesJson.cpp");
    if (!sf.open(QIODevice::WriteOnly | QIODevice::Truncate)) return false;
    QTextStream out(&sf); out.setCodec("UTF-8");
    out << "// Auto-generated by SimParamEditor\n";
    out << "#include \"Instances.h\"\n";
    out << "#include \"json.hpp\"\n\n";
    out << "using nlohmann::json;\n\n";
    // 为每个实例生成 to_json/from_json 函数
    for (int i = 0; i < instances.size(); ++i) {
        const InstanceMetadata& inst = instances.at(i);
        const ParamMetadata* tn = findTypeNodeByPath(root, inst.typePath);
        if (!tn) continue;
        const QString typeName = sanitize(tn->name);
        const QString instName = toLowerCamel(inst.name);
        out << "json toJson_" << instName << "(const " << typeName << "& v) { json j;\n";
        renderToJson(out, *tn, "v", "j", 2);
        out << "  return j; }\n";
        out << typeName << " fromJson_" << instName << "(const json& j) { " << typeName << " v{};\n";
        renderFromJson(out, *tn, "v", "j", 2);
        out << "  return v; }\n\n";
    }
    return sf.commit();
}

bool CppGenerator::generateStruct(const ParamMetadata& node, const QString& outDir)
{
    const QString structName = sanitize(node.name);
    const QString headerName = structName + ".h";
    const QString sourceName = structName + ".cpp";

    // header
    QSaveFile hf(outDir + "/" + headerName);
    if (!hf.open(QIODevice::WriteOnly | QIODevice::Truncate)) return false;
    QTextStream hout(&hf);
    hout.setCodec("UTF-8");
    hout << "// Auto-generated by SimParamEditor\n";
    hout << "#pragma once\n";
    hout << "#include <cstdint>\n";
    hout << "#include <QString>\n\n";
    hout << "struct " << structName << " {\n";
    for (const auto& c : node.children) {
        if (c.type == ParamType::STRUCT) {
            hout << "    " << sanitize(c.name) << " " << sanitize(c.name) << ";\n"; // nested struct as member by name type
        } else if (c.type == ParamType::CHAR_ARRAY && c.arraySize > 0) {
            hout << "    char " << sanitize(c.name) << "[" << c.arraySize << "];\n";
        } else {
            const QString ct = cppTypeFor(c.type);
            if (!ct.isEmpty())
                hout << "    " << ct << " " << sanitize(c.name) << ";\n";
        }
    }
    hout << "};\n";
    if (!hf.commit()) return false;

    // source (empty for now, placeholder)
    QSaveFile sf(outDir + "/" + sourceName);
    if (!sf.open(QIODevice::WriteOnly | QIODevice::Truncate)) return false;
    QTextStream sout(&sf);
    sout.setCodec("UTF-8");
    sout << "// Auto-generated by SimParamEditor\n";
    sout << "#include \"" << headerName << "\"\n";
    if (!sf.commit()) return false;

    return true;
}


